"""
Weekly report generator.

Produces "Global AMR & Infectious Disease Weekly Report" as Markdown + HTML in
the reports/ folder. Open the HTML in a browser and Print -> Save as PDF to get
a PDF (no heavy PDF library needed for the MVP).
"""
from datetime import date, timedelta

import db
from analysis import trends


def _recent_documents(days: int, event_types: list[str] | None = None, limit: int = 8):
    date_expr = "COALESCE(NULLIF(d.published_date,''), substr(d.fetched_at,1,10))"
    cutoff = (date.today() - timedelta(days=days)).isoformat()
    sql = f"""
        SELECT d.id, d.title, d.url, d.source, e.event_type,
               {date_expr} AS day, e.summary
        FROM documents d
        LEFT JOIN extractions e ON e.document_id = d.id AND e.is_active = 1
        WHERE {date_expr} >= ?
    """
    params = [cutoff]
    if event_types:
        placeholders = ",".join("?" * len(event_types))
        sql += f" AND e.event_type IN ({placeholders})"
        params.extend(event_types)
    sql += " ORDER BY day DESC LIMIT ?"
    params.append(limit)
    with db.get_conn() as conn:
        return [dict(r) for r in conn.execute(sql, params).fetchall()]


def _bullets(rows) -> list[str]:
    out = []
    for r in rows:
        title = (r.get("title") or "Untitled").strip()
        out.append(f"- **[{title}]({r.get('url','')})** "
                   f"— {r.get('source','')}, {r.get('day','')} "
                   f"_({r.get('event_type') or 'n/a'})_")
    return out


def build_markdown(days: int = 7) -> str:
    facts = trends.build_trend_facts(days=max(days, 30))  # 30d context for trends
    analysis = trends.narrative(facts)
    today = date.today().isoformat()

    outbreaks = _recent_documents(days, ["Outbreak", "Emerging Pathogen"])
    amr = _recent_documents(days, ["Antimicrobial Resistance", "New Drug"])
    papers = _recent_documents(days, ["Research Article", "Antimicrobial Resistance", "Emerging Pathogen"])
    trials = _recent_documents(days, ["Clinical Trial"])
    guidelines = _recent_documents(days, ["Guideline"])

    def section(title, rows, empty="_No items this week._"):
        body = "\n".join(_bullets(rows)) if rows else empty
        return f"## {title}\n\n{body}\n"

    md = [
        f"# Global AMR & Infectious Disease Weekly Report",
        f"_Generated {today} · window: last {days} days · trend context: 30 days_\n",
        "## AI Trend Analysis\n",
        analysis + "\n",
        section("This week's key infectious-disease events", outbreaks),
        section("This week's AMR highlights", amr),
        section("Notable publications", papers),
        section("Clinical trials", trials),
        section("Guidelines", guidelines),
        "## Snapshot (last 30 days)\n",
    ]

    def table(title, records, cols=("value", "documents")):
        if not records:
            return f"**{title}:** _none_\n"
        head = " | ".join(cols)
        sep = " | ".join("---" for _ in cols)
        lines = [f"**{title}:**\n", f"| {head} |", f"| {sep} |"]
        for r in records[:8]:
            lines.append("| " + " | ".join(str(r.get(c, "")) for c in cols) + " |")
        return "\n".join(lines) + "\n"

    md.append(table("Top pathogens", facts["top_pathogens"]))
    md.append(table("Top resistance mechanisms", facts["top_genes"]))
    md.append(table("Top antibiotics", facts["top_antibiotics"]))
    md.append(table("Most active countries", facts["top_countries"]))
    md.append("\n---\n_Data: WHO DON, CDC, ECDC, PubMed, ClinicalTrials.gov, GLASS "
              "(open-source). Generated by the ID-Intel platform._\n")
    return "\n".join(md)


def _markdown_to_html(md: str) -> str:
    """Very small Markdown->HTML so we need no extra dependency."""
    import html
    import re
    lines = md.split("\n")
    html_lines, in_table, in_list = [], False, False

    def close_list():
        nonlocal in_list
        if in_list:
            html_lines.append("</ul>")
            in_list = False

    for line in lines:
        raw = line.rstrip()
        if raw.startswith("| "):
            cells = [c.strip() for c in raw.strip("|").split("|")]
            if set("".join(cells)) <= set("-: "):
                continue  # separator row
            if not in_table:
                html_lines.append("<table>")
                in_table = True
            tag = "th" if all(c.startswith("**") or c in ("value", "documents") for c in cells) else "td"
            row = "".join(f"<{tag}>{_inline(html.escape(c))}</{tag}>" for c in cells)
            html_lines.append(f"<tr>{row}</tr>")
            continue
        elif in_table:
            html_lines.append("</table>")
            in_table = False

        if raw.startswith("# "):
            close_list(); html_lines.append(f"<h1>{_inline(html.escape(raw[2:]))}</h1>")
        elif raw.startswith("## "):
            close_list(); html_lines.append(f"<h2>{_inline(html.escape(raw[3:]))}</h2>")
        elif raw.startswith("- "):
            if not in_list:
                html_lines.append("<ul>"); in_list = True
            html_lines.append(f"<li>{_inline(html.escape(raw[2:]))}</li>")
        elif raw == "---":
            close_list(); html_lines.append("<hr>")
        elif raw == "":
            close_list()
        else:
            close_list(); html_lines.append(f"<p>{_inline(html.escape(raw))}</p>")
    close_list()
    if in_table:
        html_lines.append("</table>")
    body = "\n".join(html_lines)
    return f"""<!doctype html><html><head><meta charset="utf-8">
<title>Weekly Report</title>
<style>
body{{font-family:-apple-system,Segoe UI,Roboto,sans-serif;max-width:820px;margin:2rem auto;padding:0 1rem;line-height:1.55;color:#1a1a2e}}
h1{{border-bottom:3px solid #0b7285;padding-bottom:.3rem}}
h2{{color:#0b7285;margin-top:1.8rem}}
table{{border-collapse:collapse;margin:.5rem 0}}
th,td{{border:1px solid #ccc;padding:4px 10px;text-align:left}}
th{{background:#e3fafc}}
a{{color:#0b7285}}
</style></head><body>{body}</body></html>"""


def _inline(text: str) -> str:
    import re
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"_(.+?)_", r"<em>\1</em>", text)
    text = re.sub(r"\[(.+?)\]\((.+?)\)", r'<a href="\2">\1</a>', text)
    return text


def generate(days: int = 7) -> dict:
    import config
    from analysis.trends import redact_secrets
    md = redact_secrets(build_markdown(days))   # never write API keys into a report
    html = redact_secrets(_markdown_to_html(md))
    stamp = date.today().isoformat()
    md_path = config.REPORTS_DIR / f"weekly_report_{stamp}.md"
    html_path = config.REPORTS_DIR / f"weekly_report_{stamp}.html"
    md_path.write_text(md, encoding="utf-8")
    html_path.write_text(html, encoding="utf-8")
    return {"markdown": str(md_path), "html": str(html_path), "content": md}


if __name__ == "__main__":
    out = generate()
    print("Wrote:", out["markdown"])
    print("Wrote:", out["html"])
